version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Spike.Box.sln

before_build: 
  - cmd: nuget restore Spike.Box.sln

after_test:
  - ps: .\Deploy\pack.ps1

artifacts:
  - path: Spike.Box.Runtime\bin\Release\FSharp.Core.dll.dll
    name: FSharp.Core.dll.dll
  - path: Spike.Box.Runtime\bin\Release\Spike.Scripting.dll.dll
    name: Spike.Scripting.dll.dll
  - path: Spike.Box.Runtime\bin\Release\Spike.Scripting.Runtime.dll.dll
    name: Spike.Scripting.Runtime.dll.dll
  - path: Spike.Box.Runtime\bin\Release\Spike.Box.Runtime.dll
    name: Spike.Box.Runtime.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rU+w5deWOMiUmQES2u4bz1o0ElWYIfjxKVokp+QUjjidbGiRJwK6s1LcTNRrAde3
  artifact: /.*\.nupkg/
