//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spike.Box.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spike.Box.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; ng-app=&quot;app&quot; ng-controller=&quot;box&quot; box-app=&quot;{{app}}&quot; box-host=&quot;{{host}}&quot; box-view=&quot;{{view}}&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;{{title}}&lt;/title&gt;
        ///
        ///    &lt;script src=&quot;//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;//ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;/js/spike.box.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; hr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Create a JSON object only if one does not already exist. We create the
        ///// methods in a closure to avoid creating global variables.
        ///
        ///if (typeof JSON !== &apos;object&apos;) {
        ///    JSON = {};
        ///}
        ///
        ///(function () {
        ///    &apos;use strict&apos;;
        ///
        ///    function f(n) {
        ///        // Format integers to have at least two digits.
        ///        return n &lt; 10 ? &apos;0&apos; + n : n;
        ///    }
        ///
        ///    if (typeof Date.prototype.toJSON !== &apos;function&apos;) {
        ///
        ///        Date.prototype.toJSON = function () {
        ///
        ///            return isFinite(this.valueOf())
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------------------------------------------------
        /// * linq.js - LINQ for JavaScript
        /// * ver 3.0.3-Beta4 (Oct. 9th, 2012)
        /// *
        /// * created and maintained by neuecc &lt;ils@neue.cc&gt;
        /// * licensed under MIT License
        /// * http://linqjs.codeplex.com/
        /// *------------------------------------------------------------------------*/
        ///
        ///(function (root, undefined) {
        ///    // ReadOnly Function
        ///    var Functions = {
        ///        Identity: function (x) { return x; },
        ///        True: function () { return tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Linq {
            get {
                return ResourceManager.GetString("Linq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// RequireJS 2.1.11 Copyright (c) 2010-2014, The Dojo Foundation All Rights Reserved.
        /// Available via the MIT or new BSD license.
        /// see: http://github.com/jrburke/requirejs for details
        ///*/
        ///var requirejs,require,define;
        ///(function(ca){function G(b){return&quot;[object Function]&quot;===M.call(b)}function H(b){return&quot;[object Array]&quot;===M.call(b)}function v(b,c){if(b){var d;for(d=0;d&lt;b.length&amp;&amp;(!b[d]||!c(b[d],d,b));d+=1);}}function U(b,c){if(b){var d;for(d=b.length-1;-1&lt;d&amp;&amp;(!b[d]||!c(b[d],d,b));d-=1);}}function s(b,c){retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
    }
}
